### ISSUE TITLE
Support python 3.6?

### ISSUE THREAD

**Issue by estyxx** [autopub/autopub#13]
Hi :)
Just noted that autopub requires python 3.7, unfortunately, I have some environment that still uses python 3.6 (as AWS Elastic Beanstalk only recently provides support for python 3.7) so my library that is used as a dependency in those environments can't be in python 3.7... 

Would it be difficult in your opinion @justinmayer to provide support for python 3.6 as well?

Thanks :)

**Comment by justinmayer** [comment]
Hi @estyxx. 👋  I'm not aware of any Python 3.7-specific code in AutoPub, so I imagine it would simply be a matter of changing the [relevant requirement](https://github.com/autopub/autopub/blob/master/pyproject.toml#L11).

**Comment by estyxx** [comment]
Yup agree! I changed in this #14  :)
