### ISSUE TITLE
Add contributors names to changelog

### ISSUE THREAD

**Issue by patrick91** [autopub/autopub#16]
Hi @justinmayer would be possible to add an option (or make it default) that tells the bot to add the contributor name/username to the changelog? Would be nice to give recognition to people that send PRs :)

/cc @marcoacierno

**Comment by justinmayer** [comment]
Ciao Patrick! I think this is a wonderful idea. I sometimes link PR numbers manually in the changelog but often mess it up, so I welcome the notion of automating this. :thumbsup:

**Comment by justinmayer** [comment]
Many thanks to @marcoacierno for implementing this enhancement, which I merged via 7bc2e25 and released in [AutoPub 0.2.0](https://github.com/autopub/autopub/releases/tag/0.2.0). 🎉 

@patrick91 / @ernestoarbitrio: Thank you for suggesting this feature!
