### ISSUE TITLE
Include dates with release

### ISSUE THREAD

**Issue by minchinweb** [autopub/autopub#19]
One of the pieces I look for in changelog is the date of the releases. This helps me understand how recently a project has been update, and so allows me to guess what versions of Python it might support, for example.

Would it be possible for AutoPub to automatically include the date the release is cut when it updates the changelog? I envisions this either as an extension to the header (current just the release version) or as a single line just under the header.

**Comment by justinmayer** [comment]
I am… confused. AutoPub already appends the release date right after the version number in every `CHANGELOG.md` file that I've ever seen it touch. For example: https://github.com/pelican-plugins/image-process/commit/ab43687762b83eb291858e04b16d4e57b32ecbb8#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR4

**Comment by justinmayer** [comment]
@MinchinWeb: Could you elaborate? As I mentioned in my last comment, dates are already appended to the version number in all AutoPub-generated change-log entries.

**Comment by minchinweb** [comment]
@justinmayer I was certain the dates were missing. I've gone back and looked these last two nights at the various projects I was looking at that original night, and can't find the missing dates... I'm at a loss. Sorry for the chaos. Thanks for all you do.
