### ISSUE TITLE
autopub fails to push release to PyPI

### ISSUE THREAD

**Issue by minchinweb** [autopub/autopub#27]
So I just pushed an update to (Pelican's) image-process, and autopub errored out saying the git tag didn't exist (but it does, it created it), and so didn't add the wheel to the GitHub release or push the wheel to PyPI.

- GitHub Action run -- https://github.com/pelican-plugins/image-process/runs/5613836396?check_suite_focus=true
- Release -- https://github.com/pelican-plugins/image-process/releases/tag/3.0.0

Any ideas on how to fix this? I think it's something in autopub that broke....

**Comment by patrick91** [comment]
Hi @MinchinWeb, I think this issue is duplicated, see: https://github.com/autopub/autopub/issues/26

My fix seems to work most of the time, though I did have the same issue once (but all the other releases went through just fine) :)

**Comment by minchinweb** [comment]
Yes it does look like a duplicate of #26. I'll close this for now then.

(Except it appears you can't close issues from your phone...)
