### ISSUE TITLE
Make GitHub release optional

### ISSUE THREAD

**Issue by estyxx** [autopub/autopub#5]
Hello, 

I would like to use this tool to automate the versioning and releases of my project, but as our softwore is not open source and is not hosted on GitHub should be better to not have to install `githubrelease` library in the deploy process...

Maybe just a try/except in the import could already fix...

**Comment by justinmayer** [comment]
Ciao Ester! Long time no see. I hope you are well.

I just submitted a pull request that I believe should address this issue. Would you please take a look and let me know your thoughts?

**Comment by estyxx** [comment]
Hey! Fine thanks! What about you?? 
Looks great thanks!

**Comment by justinmayer** [comment]
Great. Merging now, which will of course release a new version of AutoPub. 💫
